//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerNET.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroUnidade
    {
        public int idLibroUnidades { get; set; }
        public int idLibro { get; set; }
        public int idUbicacion { get; set; }
        public string Codigo { get; set; }
    
        public virtual UBICACION UBICACION { get; set; }
    }
}
