//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerNET.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public string idLibroUnidades { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Venta Venta1 { get; set; }
        public virtual Venta Venta2 { get; set; }
    }
}
